### ISSUE TITLE
GoogleMap 사용 시 Fragment와 Activity간 데이터 이동방법

### ISSUE THREAD

**Issue by Seonmi-Hwang** [Seonmi-Hwang/study#15]
@jongfeel
안녕하세요 멘토님! 잘 지내시죠? :) 
학교 프로젝트를 진행하다가 의미없는 삽질인 것 같아서
멘토님께 오랜만에 도움을 청하게 되었습니다.

제가 만들고자 하는 앱이 Navigation Drawer를 필요로 해서
학교에서 배우지 않은 부분이었지만 (수업 때는 매번 Empty Activity를 생성했습니다.)
**Navigation Drawer Activity**를 선택하였습니다.

**GoogleMap**이 필요해서 **/res/layout/fragment_home.xml** 에 **SupportMapFragment**를 만들었는데
MainActivity.java에서 GoogleMap을 사용하려고 하니 사용이 되지 않아서 
여러 가지 시도를 해보다가 **HomeFragment.java에서 onMapReady를 구현**하니
앱이 다운되지 않고 살아는 있게 된 상태입니다.

아래는 **HomeFragment.java** 코드 중 일부입니다.
![image](https://user-images.githubusercontent.com/50273050/71362245-e1d1ad00-25d8-11ea-9b37-10de617799ca.png)

HomeFragment에서는 GoogleMap과 관련된 모든 부분을 작성할 수는 없는 것 같아서
MainActivity.java에서 Marker를 적용하려고 하니 googleMap 객체가 필요한데

GoogleMap 객체를 가져오는 방법도 안되고,
MarkerOptions를 HomeFragment에서 Marker에 setting해주고 (setter를 만들었습니다)
해당 Marker를 다시 MainActivity.java로 가져오는 방법(getter)도 안되더라구요. 

아래는 **GoogleMap 객체를 getter로 가져오는 방법을 시도한 코드**입니다.
![image](https://user-images.githubusercontent.com/50273050/71362028-31fc3f80-25d8-11ea-82d1-6a1db376deae.png)

아래는 **HomeFragment에 제 나름의 getter, setter를 만들어본 결과**입니다.
![image](https://user-images.githubusercontent.com/50273050/71362331-13e30f00-25d9-11ea-8d76-1eb0be72d491.png)

PlaceListener 자체를 HomeFragment에 옮기고 싶은데 
runOnUiThread 메소드(?)가 Fragment 클래스에는 없는 모양입니다..

전체적인 코드는 AndroidProject 폴더 내부에 있습니다.

원활하게 동작되려면 어떻게 해야할까요?
HomeFragment에서 MainActivity로 GoogleMap을 가져오는 방법이 있을까요?
아니면 다른 방법을 써야하나요?

하루종일 이것 때문에 시간을 허비하고 있습니다. 도와주세요..

**Comment by jongfeel** [comment]
@Seonmi-Hwang 

안녕하세요.

공부를 열심히 하고 계신거 같아서 반갑네요.

정확한건 당장 봐드릴 수는 없을 듯 한데

https://webnautes.tistory.com/647
https://bitsoul.tistory.com/145

보셨을 수도 있지만 위에 링크에서 힌트를 얻어보시면 어떨까요?

그 사이 해결하셨을 수도 있고 아직 시간을 허비하고 계실 수도 있긴 한데
제가 자세하게 봐 드릴 시간이 내일 저녁이나 되야 할 거 같습니다.

**Comment by Seonmi-Hwang** [comment]
@jongfeel 
그렇군요.
보내주신 링크는 수업 때 했던 것과 같은 내용이네요!
제가 시도한 경우는 Navigation Drawer Activity여서 찾아봐도 잘 안나오더라구요.
최대한 해결해보겠지만 시간되실 때 한 번 봐주시면 감사하겠습니다!

**Comment by jongfeel** [comment]
@Seonmi-Hwang 

AndroidProject/Don't Afraid의 Android project 인 것으로 보이는데 이걸로 디버깅을 진행해 볼께요.

제 개발환경은 아래 그림을 참고해 주세요

![image](https://user-images.githubusercontent.com/17442457/71436444-d09bb400-2730-11ea-817a-404abb81eb22.png)
![image](https://user-images.githubusercontent.com/17442457/71436416-b6fa6c80-2730-11ea-807d-3ebeece76471.png)
![image](https://user-images.githubusercontent.com/17442457/71436423-beba1100-2730-11ea-9087-bd22e683b651.png)

**Comment by jongfeel** [comment]
@Seonmi-Hwang 

몇 가지 힌트를 찾았는데요

https://webnautes.tistory.com/1080

위의 링크를 참고하셔서 코드를 조금 수정해 보시면 될 거 같아요
- PlacesListener interface 구현
- NRPlaces.Builder()로 시작하는 패턴에서 .listener 추가시 PlacesListener interface 구현한 클래스 즉 Activity를 넣을 것

그리고 Fragment 가져오는 건 

https://stackoverflow.com/questions/45247254/how-to-get-current-fragment-from-mainactivity

위의 코드를 참고하셔서 가져오면 될 거 같아요
getFramementManager()가 MainActivitiy에서 호출되는 메소드일 거에요.
그런데 이게 API 28에서는 deprecated 되서 getSupportFragmentManager()로 대신 호출하면 됩니다.
그러면 google map이 있는 fragment_home을 가져올 수 있을 거에요.

조금 해보시고 필요한게 있으면 계속 issue를 통해 확인해 보면 될 거 같아요.

Merry Christmas!

**Comment by Seonmi-Hwang** [comment]
@jongfeel 

친절하고 자세한 답변 정말 정말 감사드립니다.
교수님도 메일에 잘 답장을 안해주셔서 혼자 헤매다 빛을 찾은 느낌이에요..

기존 프로젝트에서 수정해보려하니 PlaceListener를 MainActivity에서 implements 했느냐
아니면 내부에서 클래스 객체 선언(?)을 했느냐의 차이인 것 같습니다.

그리고 Fragement 객체를 가져오는 것은 될 것 같은데 Navigation Drawer Activity에서는
fragement_\*.xml에 버튼이나 텍스트나 어떤 것을 놓든지간에
\*Fragment.java에서 설정을 해줘야 화면에 나온다는 것을 깨달았습니다.

위 사실을 깨닫고 제가 Fragment와 ViewModel 클래스를 구현하는 것에 대한 지식이 전혀 없어서 
기한 내에 못할 것 같다는 생각이 들어서 어제 content_main 내부 fragment가 mobile_navigation을 통해서 동적으로 자연스럽게 변경되는 것을 포기하고 
아래 블로그를 참고하여 슬라이드 메뉴 구현까지 했습니다..

https://lktprogrammer.tistory.com/168

저는 Navigation Drawer에서 메뉴 아이템을 클릭할 때 activity 자체를 바꾸고 싶은데
그러면 acitivity_main과 app_bar_main과 같은 액티비티들이 각 바뀌는 액티비티마다
하나씩 더 생성되어야만 가능하겠죠..?

중복되는 코드들이 많아져서 비효율적이지만 Navigation Drawer Activity를 사용하지 않는다면 그 방법밖에 없는 듯 합니다.. 혹시 더 좋은 방법을 아시거나 제가 잘못된 방향으로 흘러가는 것 같다면 조언해주시면 감사하겠습니다!

현재 진행상황은 메뉴 아이템을 클릭했을 때 openapi를 받아오는 액티비티를 띄우는 것까진 되는데
openapi를 받아오는 과정에서 network error가 발생하는 문제가 생긴 상황입니다. 여유가 되신다면 새로운 issue에서 도움을 주신다면 감사하겠습니다!

멘토님 답변 덕분에 다시 진행하고 있는 프로젝트에서도 보완할 부분을 찾을 수 있었습니다. 
감사합니다.

즐거운 크리스마스 되세요 :)

**Comment by jongfeel** [comment]
@Seonmi-Hwang 

안드로이드 activity들 끼리의 교류(?)가 잘 안되는 느낌이 들어서 코드가 중복된다는 느낌이 들면
조금 더 생각해 보시고 refactoring을 바로 해보시는게 좋습니다.
어쩌면 이런 기회에 코드 중복성 제거+재사용에 대한 걸 배울 수 있으니까요.

그리고 잘못된 방법은 없습니다.
생각한 대로 구현했느냐 안했느냐의 차이가 없다면 일단 잘 하신 거고요.
거기에 조금 더 software engineering을 한다면 더 좋겠죠.

**Comment by Seonmi-Hwang** [comment]
@jongfeel 

refactoring이라는게 '일련의 리팩토링을 적용하여 겉으로 보이는 동작의 변화 없이 소프트웨어 구조를 바꾸다'를 말씀하시는거 맞나요?

네 일단 생각한 대로 구현이 된 후에 효율적으로 바꿔보도록 하겠습니다!
감사합니다 :) 👍
