### ISSUE TITLE
OPEN API 사용 시 404 Error

### ISSUE THREAD

**Issue by Seonmi-Hwang** [Seonmi-Hwang/study#16]
@jongfeel

안녕하세요 멘토님! 같은 프로젝트에 대한 두 번째 질문입니다..
지금 공공데이터포털에서는 표준데이터들에서 OPEN API가 비정상적으로 작동되고 있습니다.
한 달 전만 해도 정상적으로 작동했는데 똑같이 요청했는데 계속 로딩만 되고 있습니다.

그래서 일단 다른 api를 사용해보고 있는데 이것도 문제가 발생했습니다.
제가 사용할 api에 대한 정보는 아래에 있습니다.

http://116.67.77.182/index.jsp

**AndroidManifest.xml**에 **android:usesCleartextTraffic="true"** 도 설정했고,
Log.d로 요청한 url을 콘솔창에 출력하게 해서 그 url을 클릭하면 정상적으로 xml화면이 나옵니다.

http://116.67.77.182/openapi/SOCitysStats

그런데 왜 404 에러가 자꾸 발생하는지 모르겠습니다. 도와주세요..!

![image](https://user-images.githubusercontent.com/50273050/71443354-c936d380-274d-11ea-8a73-901bf252043f.png)

**Comment by jongfeel** [comment]
@Seonmi-Hwang 

https://github.com/Seonmi-Hwang/study/blob/204b4fbaee294c86db5c494cc5c11554ef8cec01/AndroidProject/Don't%20Afraid/app/src/main/java/dduwcom/mobile/ma02_20170995/SexOffenderInfoActivity.java#L167

getNetworkConnection() 메소드에서
setRequestProperty를 추가로 호출해 보세요.

> conn.setRequestProperty("Content-Type", "application/xml");

아래 링크를 참고해 보셔서 모든 가능성을 열어두고 찾아보면 답이 나올겁니다.
https://arabiannight.tistory.com/entry/%EC%95%88%EB%93%9C%EB%A1%9C%EC%9D%B4%EB%93%9CAndroid-HttpUrlConnection-XML-%EB%B0%A9%EC%8B%9D%EC%9C%BC%EB%A1%9C-Request-Response-%ED%95%98%EA%B8%B0

**Comment by Seonmi-Hwang** [comment]
@jongfeel

헉 됐어요!!!
```java
conn.setRequestProperty("Content-Type", "application/xml");
```
이 부분을 추가했을 때는 같은 에러가 발생했는데 아래 코드를 추가하니까 정상적으로 실행됐습니다!

```java
conn.setRequestProperty("Accept", "application/xml");
```
왜인지는 모르겠지만 xml 형식으로 받아와지지 않았나봅니다.
정말 감사합니다!!
