### ISSUE TITLE
사진 첨부한 MMS 전송 

### ISSUE THREAD

**Issue by Seonmi-Hwang** [Seonmi-Hwang/study#17]
@jongfeel

안녕하세요 멘토님!
아마 이번이 지금 프로젝트의 마지막 질문이 될 것 같습니다.

마감 기한이 얼마 남지 않았는데요..
한참 헤매다가 다급한 마음에 질문드립니다.

MMS로 문자 메세지를 만드는 코드는 모두 완성되었습니다.
그런데 전송 자체가 자동으로 되지 않습니다.

제가 개발한 앱에서 메세지를 전송까지 시킬 순 없는건가요?

![Screenshot_1577440693](https://user-images.githubusercontent.com/50273050/71512725-d8975780-28da-11ea-9570-3b2fc3b4529c.png)

전송버튼을 누르면 이렇게 메세지 앱이 실행되고 텍스트가 적혀있는데 
전송은 직접 전송버튼을 눌러야만 발송되는 상태입니다.
(MMS도 구현이 되었는데 에뮬레이터 상에서는 나오지 않습니다.)

SmsManager를 사용하면 바로 전송이 잘 되던데 
MMS는 intent를 사용하니까 안되는 것 같습니다. sms도 intent를 쓰니까 마찬가지더라구요.
intent를 사용하면 어쩔 수 없는건가요??

**Comment by jongfeel** [comment]
@Seonmi-Hwang 

주말에 일정이 있어서 이제야 답변을 드리게 됐네요.

그런데 검색해보셔서 아셨겠지만 SMS 말고 MMS는 통신사마다 규격이 있어서
전송까지 저절로 되지는 않는 걸로 알고 있습니다.
(저도 여기까지만 알고 있는 상태였습니다)

검색해 보니
방법이 여러가지 나오는데
https://wewave.tistory.com/25

별도의 라이브러리 코드를 사용하면 통신사에 구애받지 않고 전송가능한 걸로 나와 있네요

사실 특별히 전송 자체가 안되는 것 아니라면 문제는 없을 것 같은데
이런 이슈가 있다는 걸 발표할 때 어필한다면 어떨까요?

**Comment by Seonmi-Hwang** [comment]
@jongfeel 

결국 자동 전송 기능은 구현 못하고 제출했습니다!!
아 역시 원래는 통신사마다 달리 해주는 방법을 사용해야 했군요.
너무 복잡하고 어려워서 그 부분 말고 다른 부분을 찾고 있었는데..

sendMMS3 은 건드려보다가 시간이 없어서 그냥 제출했습니다.
다른 과제가 끝난 후에 다시 건드려 볼 생각입니다. 하핫.

아무래도 응급 상황에서 사용할 앱을 만드는지라
문제는 없지만 자동 전송을 시키는게 저의 작은 욕심이었어요ㅋㅋㅋ

아쉽게도 발표는 없었어서 교수님께 질문만 남겼었습니다.
그래도 멘토님 덕분에 많이 배웠습니다! 
바쁜 와중에도 틈틈이 답변해주셔서 감사합니다.

아 혹시 멘토링은 아무때나 연락드려서 신청(?)해도 되나요??
따로 신청기간(?) 같은게 있나 해서요.

**Comment by jongfeel** [comment]
@Seonmi-Hwang 
벌써 제출하셨군요.

그런데 발표는 안했다고 하니 조금 아쉬움이 남을 수도 있을 것 같긴 해요.
제가 최대한 많이 도와드린다고 했는데 잘 진행해 주셔서 다행이네요.

issue를 close 하셔서 멘토링 관련된 내용은 메일로 보내드릴께요.
