### ISSUE TITLE
Bucket 문제 해결 방법

### ISSUE THREAD

**Issue by Seonmi-Hwang** [Seonmi-Hwang/study#18]
@jongfeel

안녕하세요 멘토님.
일단 2020년 새해 복 많이 받으세요!
저는 아직도 이 과제로 인해 종강을 못했습니다..

내일 마감인데 아직까지도 감이 잘 안잡혀서요.
문제는 아래와 같습니다.

![image](https://user-images.githubusercontent.com/50273050/71654418-18e05500-2d75-11ea-964f-998dca88ca50.png)
![image](https://user-images.githubusercontent.com/50273050/71654432-24cc1700-2d75-11ea-9155-9517e6019ba0.png)

작년에 알고리즘 수강하신 분에게 힌트를 얻은건 
우선 입력받은 값들을 정렬한 다음에 전체 중 버킷의 개수만큼 순열로 뽑고,
한 세트씩 뽑을 때마다 오차를 계산해주고, 오차가 가장 적은 세트가 정답이라고 하는데요.

말이 잘 이해가 안되기도 하고 왜 정렬하는지 왜 순열인지도 잘 모르겠지만 일단 버킷의 개수만큼 뽑고 나서(뽑은게 대표숫자가 맞는지도 잘 모르겠습니다) 그 대표숫자를 기준으로 다른 숫자들을 어떻게 그룹화 하는지도 감이 안옵니다..

아래는 이 문제의 테스트 케이스 중 하나입니다.
```
40 3 3 6 7 5 3 5 6 2 9 1 2 7 0 89 83 86 80 86 82 86 81 88 87 89 82 80 162 163 167 165 169 162 162 168 169 167 163 166 161 162

답 : 334
```

이것에 대한 설명은 아래와 같습니다.
```
위의 예에서는 세 그룹이 각각
3 6 7 5 3 5 6 2 9 1 2 7 0
89 83 86 80 86 82 86 81 88 87 89 82 80
162 163 167 165 169 162 162 168 169 167 163 166 161 162
으로 나누어지며 대표값은 각각 4/85/165입니다.
```
대표값이 주어진 숫자 중에 없는 것 같은데 그냥 임의로 정하는 걸까요?
위에 힌트 말고 다른 방법이 있는지 아니면 힌트로 해결하면 되는건지 
어떤 식으로 해결해야할지 도움을 주신다면 감사하겠습니다!

**Comment by jongfeel** [comment]
@Seonmi-Hwang 

2020년에도 계속해서 만나게 되는군요.
새해 복 많이 받으세요.

적어주신 것 대로 이해를 하셔서 진행해 보면 될 거 같아요.
알고리즘 문제에서 힌트를 준다고 해서 풀 수 있는 건 아니라서요.
이해를 잘 해보시면 좋을 것 같아요.
문제에 이미 이해를 할 수 있는 조건들이 적혀 있습니다.

첫번째 bucket에서 대표 숫자를 구한다고 했을 때
가장 작은 숫자부터 가장 큰 숫자까지 대표 숫자라고 가정하고 오차를 계산해 보면 가장 작은 수가 나오지 않을까요?
가장 작은 숫자: 0
가장 큰 숫자: 9

0일 때 오차
(3-0)^2 + (6-0)^2 + (7-0)^2 + ... + (0-0)^2 = 328
1일 때 오차
(3-1)^2 + (6-1)^2 + (7-1)^2 + ... + (0-1)^2 = 249
2일 때 오차
...
3일 때 오차
...
4일 때 오차
(3-4)^2 + (6-4)^2 + (7-4)^2 + ... + (0-4)^2 = 72

이렇게 해서 9일 때 오차를 쭉 계산해 보고 그 중에 가작 작은 숫자가 걸려든 숫자가 대표 값이겠죠. 그게 4가 되는 거고요.

이정도 힌트라면 어떨까요?

**Comment by Seonmi-Hwang** [comment]
@jongfeel

아하 오차를 구하는 부분은 이해가 됩니다!
그런데 저는 bucket을 어떻게 나눠야 할지가 이해가 잘 안됩니다.

가장 작은 숫자부터 가장 큰 숫자를 정한다는게
일단 bucket에 아이템들이 알맞게 나눠진다는 것을 전제로 하는 것으로 이해하고 있습니다.

만약 bucket이 3개일 경우
일단 정렬을 한 후에 적당한 선에서 끊어서 숫자들을 bucket에 세 가지로 나눠야 하는데
그 적당한 선을 어떻게 잡을지가 알쏭달쏭합니다..

-------------------------------------------------------------------

중복순열로 bucket에 몇 개의 숫자가 들어갈지를 뽑는 것으로 방금 이해 했습니다. 
이걸 생각하기가 굉장히 어려웠습니다..

멘토님이 힌트를 주신대로 오차도 잘 구해보도록 하겠습니다!
감사합니다 :)
